### ISSUE TITLE
Previous header always visible when I try to clear the list and add new element

### ISSUE THREAD

**Issue by Vaudey** [TellH/RecyclerStickyHeaderView#4]
Hello thanks for you sticky header recyler view, I got an issue if I scroll the list and then if I try to remove all element in the list and add some new one, the last stickyheader is always visible on top. If I don't scroll the list all works fine and the last sticky header don't appear

What is the good way for remove every element in the list I try to create a new adapter or use adapter.clear(recyclerView) or adapter.clearViewBinderCache() nothing works and create some new error.
I think that when I'm scrolling the last sticky header is store somewhere and when I try to delete element I don't delete this sticky header 

Thanks for your help

**Comment by TellH** [comment]
Thanks for your feedback. You can try the new release version.
```
	dependencies {
	        compile 'com.github.TellH:RecyclerStickyHeaderView:1.1.0'
	}
```
